
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.05
name: Test-SubCalls
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::Builder::Tester: 1.02
requires: 
  Test::More: 0.60
  perl: 5.6.0
  File::Spec: 0.80
  Hook::LexWrap: 0.20
abstract: Track the number of times subs are called
