abstract: Track the number of times subs are called
author: 'Adam Kennedy <cpan@ali.as>, L<http://ali.as/>'
build_requires:
  Test::Builder::Tester: 1.02
distribution_type: module
generated_by: Module::Install version 0.50
license: perl
name: Test-SubCalls
no_index:
  directory:
    - inc
    - t
requires:
  File::Spec: 0.80
  Hook::LexWrap: 0.20
  Test::More: 0.60
  perl: 5.6.0
version: 0.03
